apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
- ../default

patches:
- path: manager-pvc-patch.yaml
  target:
    kind: StatefulSet
    name: controller-manager

